### ISSUE TITLE
VLAN

### ISSUE THREAD

**Issue by HarmK2** [rundqvist/docker-openvpn-tinyproxy#1]
Hi rundqvist,
I can't get this to work in a container connected to a VLAN, only with the network in HOST mode. Is that intended?
In HOST mode it works like a charm! 
Thank you!

**Comment by rundqvist** [comment]
Hi,

Have you entered the environment variable NETWORK?
I haven't tested it with VLAN, but it works fine in bridged mode if NETWORK is entered correctly.

Regards
/rundqvist

**Comment by HarmK2** [comment]
Hi Mattias,

Yes in bridge mode it works like a charm. Thank you for that. In a vlan is does not connect to the lan. It does to the vpn provider, but you cannot connect to the container.

Regard,
Harm

⁣TypeApp voor Android downloaden ​

Op 5 sep. 2020 20:59, om 20:59, Mattias Rundqvist <notifications@github.com> schreef:

**Comment by rundqvist** [comment]
Could you please provide your vlan settings (preferably in 'docker network create'-command line format), and I will investigate it.

**Comment by HarmK2** [comment]
I will, as soon as i am back from a short holiday.

⁣TypeApp voor Android downloaden ​

Op 6 sep. 2020 19:51, om 19:51, Mattias Rundqvist <notifications@github.com> schreef:
